country_carrier_detection:
  logger:
    service_id: 'logger'
  cache:
    service_id: 'cache.app'
  db_paths:
    connection_type_database: "%kernel.root_dir%/../var/geoip-databases/GeoIP2-Connection-Type.mmdb"
    country_database: "%kernel.root_dir%/../var/geoip-databases/GeoIP2-Country.mmdb"
    isp_database: "%kernel.root_dir%/../var/geoip-databases/GeoIP2-ISP.mmdb"


device_detection:
  logger:
    service_id: 'logger'
  cache:
    service_id: 'cache.app'
  db_paths:
    optimized_database: "%kernel.root_dir%/../var/devicedetection/optimized"
    database: "%kernel.root_dir%/../var/devicedetection/database/db.json"


extras:
  signature_check:
    request_parameter: signature
    secret_key: secretkey
  cache:
    redis_host: 127.0.0.1
    redis_port: 6378
    redis_prefix: vdefault
    use_array_cache: false