services:
    app.cache.default:
        class: ExtrasBundle\Cache\CacheServiceWrapper
        arguments: ['@app.cache.redis_default']

    app.cache.default_factory:
        class: ExtrasBundle\Cache\CacheFactoryWrapper
        arguments: ['@app.cache.redis_factory']

    app.cache.redis_factory:
        class: ExtrasBundle\Cache\Redis\RedisCacheServiceFactory
        arguments: ['@app.cache.redis_connection_provider','v%app_version_hash%']

    app.cache.redis_connection_provider:
        class: ExtrasBundle\Cache\Redis\RedisConnectionProvider
        arguments:
            - "_redis_host_placeholder_"
            - "_redis_port_placeholder_"
            - "_redis_prefix_placeholder_"

    app.cache.redis_default:
        class: ExtrasBundle\Cache\Redis\RedisCacheService
        factory: [ '@app.cache.redis_factory', 'createCacheService']
        arguments: ['0', 'default']


    app.cache.array_default:
        class: ExtrasBundle\Cache\ArrayCache\ArrayCacheService
        factory: [ '@app.cache.array_factory', 'createCacheService']
        arguments: ['0', 'default']


    app.cache.array_factory:
        class: ExtrasBundle\Cache\ArrayCache\ArrayCacheFactory