services:
    app.cache.default:
        class: ExtrasBundle\Cache\CacheServiceWrapper
        arguments: ['@app.cache.default.translation']

    app.cache.default_factory:
        class: ExtrasBundle\Cache\CacheFactoryWrapper
        arguments: ['@app.cache.redis_factory']

    app.cache.redis_factory:
        class: ExtrasBundle\Cache\Redis\RedisCacheServiceFactory
        arguments: ['@app.cache.redis_connection_provider','v%app_version_hash%']

    app.cache.redis_connection_provider:
        class: ExtrasBundle\Cache\Redis\RedisConnectionProvider
        arguments:
            - "_redis_host_placeholder_"
            - "_redis_port_placeholder_"
            - "v%app_version_hash%"

    app.predis:
        class: Predis\Client
        factory: 'app.cache.redis_factory:createCounterConnection'