services:
    app.cache.default_factory:
        class: ExtrasBundle\Cache\CacheFactoryWrapper
        arguments: ['@app.cache.array_factory']

    session.handler:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\NativeFileSessionHandler
